### ISSUE TITLE
Scrollbars displayed on boot

### ISSUE THREAD

**Issue by dominicknoetze** [Tom-Hirschberger/MMM-EmbedURL#12]
Hi
I have a problem with scrollbars present on boot, the only way of removing them is to hover mouse over the bar.
I used to use iframe, but in a recent Home Assistant update I'm unable to use iframe and have to use webview.
If you can give me some pointers I would really appreciate it.
As you can see in pic I live in a country with daily power outages.

![Screenshot 2024-02-11 at 12 56 49](https://github.com/Tom-Hirschberger/MMM-EmbedURL/assets/51887352/59bc2dce-33c4-4840-a93f-93729d55c5ca)

`      {
          module: 'MMM-EmbedURL',
          position: 'top_right',//'fullscreen_above',
          header: '',
          config: {
              embedElementType: 'webview', //iframe,webview,img
              updateInterval: '0',
              positions: 'tie',
              attributes: [
                  'frameborder=0',
                  'allowfullscreen',
                  'scrollbar=no',
              ],
              embed: [
                  'http://192.168.1.45:8123/dashboard-123/0'
              ]
          },
      },`

**Comment by Tom-Hirschberger** [comment]
Hi,

i do not have much time to test at the moment but you can style the embed element in your `custom.css`.

You may give the following snippet a chance:

```css
.MMM-EmbedURL .embed .videos.embededSubWrapper1 {
    overflow : hidden;
}
```

**Comment by dominicknoetze** [comment]
Hi 
Thank you for your response,unfortuanately it did not work.

**Comment by Tom-Hirschberger** [comment]
Sorry, my mistake. Copy & Paste problem.
Please try

```css
.MMM-EmbedURL .embed .embededSubWrapper1 { overflow : hidden; }
```

**Comment by dominicknoetze** [comment]
Hi Thomas
Thank you once again for the speedy response.
Since our last messages I have installed MMM-WebView and am having the exact problem.It appears as if the problem lies elsewhere and not with your module.If you are willing to test ill be super happy, no rush as you said you were busy at the moment.

**Comment by Tom-Hirschberger** [comment]
Got twins a few weeks ago. So time is a problem at the moment.

I think it is a simple css problem.

You can try to add a `width="200"` and `height="200"` to the attributes of the embedded element. Maybe this helps.

**Comment by dominicknoetze** [comment]
Congratulations, thats awesome man.
Enjoy your time with your new family members.

Sadly a no go with width="200" and height="200" 
I think it can wait for another day,i dont want to pressure you.
![Screenshot 2024-02-11 at 17 17 49 (2)](https://github.com/Tom-Hirschberger/MMM-EmbedURL/assets/51887352/ef690294-3b47-4bfe-9825-63708d0d46a1)

**Comment by Tom-Hirschberger** [comment]
Hi, had a few minutes today to test some things...
The idea is to make the size of the content in the embedded element independent of the size of the wrapper outside.

I added the following to my `css/custom.css`:
```css
.MMM-EmbedURL .embededSubWrapper0 {
  width:50px;
  height:100px;
  overflow:hidden;
}
```

And my embedded module configuration looks like the following:
```js
{
		module: 'MMM-EmbedURL',
		position: 'top_right',//'fullscreen_above'
		header: '',
		config:	{
			embedElementType: 'iframe', //iframe,webview,img
			updateInterval: '0',
			positions: 'tie', 
			attributes: [ 
				'frameborder=0', 
				'allowfullscreen', 
				'scrollbar=no',
				'width=500',
				'height=800',
				'style=overflow:hidden' 
			], 
			embed: [ 'https://XXX.XXX/XXX ] 
		}, 
	},
```

**Comment by dominicknoetze** [comment]
Hi Thomas

Happy to hear your twins have allowed you some time.

Since the last time we have spoken,i have upgraded my batteries and power outages are at a minimum.
I do still have the problem even after applying your fix.I think the problem has something to do on my side as I previously mentioned that MMM-WebView behaves exactly the same.I will do fresh install when time allows me.

I thank you so much for taking the time.

**Comment by dominicknoetze** [comment]
Hi Thomas
I think I have come to a point that I can identify what is going on.After some testing,i have found that custom:bar-card is causing the scrollbars.I can create a dashboard with multiple cards and not have a problem but as soon as I add custom:bar-card the bars reappear.I don't know how to fix it.

**Comment by Tom-Hirschberger** [comment]
This sounds like a styling issue of Home Assistant to me.

You can try to add a styling attribute to the embedded element but I do not know if you can style content within a Webview or Iframe element from outside.
