### ISSUE TITLE
Classes Styling Issue

### ISSUE THREAD

**Issue by FuryGear** [Tom-Hirschberger/MMM-EmbedURL#13]
Sizing attributes for different classes in config.js not taking effect.

**Comment by Tom-Hirschberger** [comment]
Can you please provide some more information...

What does your module configuration in config.js look like?

What does the CSS configuration in custom.css look like?

**Comment by FuryGear** [comment]
And then custom.cc looks like the follwoing:

.MMM-EmbedURL .embed .victron.embededSubWrapper1 {
    width    : 600px;
    height   : 700px;
    overflow : hidden;
    position : relative;
}
  
.MMM-EmbedURL .embed .embeded.victron {
    position : absolute;
    height: 600px;
    max-height: 700px;
}

**Comment by Tom-Hirschberger** [comment]
Hi, and sorry. I edited your comments and put the code into code ticks.

My section about extra classes in the example of the readme was not clear at this point.
You need to put the classes option into the config section...

```
		{
			module: "MMM-EmbedURL",
			position: "top_center",
			header: "VICTRON",	
			
			config: {
				classes: "victron",
				updateInterval: 0,
				attributes: [
					"frameborder=0",
					"width=600px",
					"height=700px",
				],
				embed: [
					"https://vrm.victronenergy.com/installation/151755/dashboard"
				]
			},
		},
```

This way everything works as expected.

**Comment by Tom-Hirschberger** [comment]
No problem. 
Great to hear it is working.
Have fun with the module.

**Comment by FuryGear** [comment]
Hi Tom. Sorry, I forgot to ask. The "allowfullscreen" attribute... what
does that allow for exactly and if I have it set in my config as follows,
is it correctly configured:

{
      module: 'MMM-EmbedURL',
      position: 'top_bar',
      header: 'VICTRON',
      classes: 'victron',
      config: {
classes: 'victron',
        updateInterval: 0,
        attributes: [
          'frameborder=0',
          'scrolling=yes',
          'allowfullscreen',
        ],
        embed: [
          'https://vrm.victronenergy.com/installation/151755/dashboard'
        ]
      }
    },

**Comment by Tom-Hirschberger** [comment]
Hi,

no problem.

The attributes are simple attributes set to the embedded element.
The site you are embedding can evaluate these attributes.
The allowfullscreen attribute is used by YouTube i.e.

18.03.2024 20:05:51 FuryGear ***@***.***>:

> 
> Hi Tom. Sorry, I forgot to ask. The "allowfullscreen" attribute... what
> does that allow for exactly and if I have it set in my config as follows,
> is it correctly configured:
> 
> {
> module: 'MMM-EmbedURL',
> position: 'top_bar',
> header: 'VICTRON',
> classes: 'victron',
> config: {
> classes: 'victron',
> updateInterval: 0,
> attributes: [
> 'frameborder=0',
> 'scrolling=yes',
> 'allowfullscreen',
> ],
> embed: [
> 'https://vrm.victronenergy.com/installation/151755/dashboard'
> ]
> }
> },
> 
> On Sat, Mar 16, 2024 at 8:14 PM Thomas Hirschberger <

**Comment by FuryGear** [comment]
Ah ok. Understood.

Is there a way to maybe force a URL such as
https://vrm.victronenergy.com/installation/151755/dashboard to display
fullscreen. Or for example my local HomeAssistant URL to view fullscreen?

**Comment by Tom-Hirschberger** [comment]
Only if the site supports it. Either by attribute (usually if the site provides elements that can be embedded like videos, charts, etc) or url parameter.

But you can set the size of the embedded Iframe to a bigger size than the embedded element and change the position in it with css. This way you can cut the content.

I added a example to the doc/configs folder which embeds a webcam and cuts the header and footer with CSS.

Maybe this is a solution working for you.

18.03.2024 20:13:43 FuryGear ***@***.***>:

> 
> Ah ok. Understood.
> 
> Is there a way to maybe force a URL such as
> https://vrm.victronenergy.com/installation/151755/dashboard to display
> fullscreen. Or for example my local HomeAssistant URL to view fullscreen?
> 
> On Mon, Mar 18, 2024 at 9:08 PM Thomas Hirschberger <

**Comment by FuryGear** [comment]
What does your module configuration in config.js look like?

    {
      module: 'MMM-EmbedURL',
      position: 'top_bar',
//    header: 'VICTRON',
      classes: 'victron',
      config: {
        updateInterval: 0,
        attributes: [
          'frameborder=0',
          'scrolling=yes',
          'allowfullscreen',
        ],
        embed: [
          'https://vrm.victronenergy.com/installation/151755/dashboard'
        ]
      }
    },

What does the CSS configuration in custom.css look like?

And I havent added the above classes: 'victron' to my custom.css file as it
is getting the default sizing from the embedURL.css which is the following:

.MMM-EmbedURL .embed .embeded {
    width: 1200px;
    height: 600px;
}

**Comment by FuryGear** [comment]
Sorry. Replied to an older response. I will give this a go. Thanks Tom

**Comment by Tom-Hirschberger** [comment]
The configs are in included the module folder within doc/configs

One file for CSS one with the module config.

18.03.2024 20:27:02 FuryGear ***@***.***>:

> 
> What does your module configuration in config.js look like?
> 
> {
> module: 'MMM-EmbedURL',
> position: 'top_bar',
> // header: 'VICTRON',
> classes: 'victron',
> config: {
> updateInterval: 0,
> attributes: [
> 'frameborder=0',
> 'scrolling=yes',
> 'allowfullscreen',
> ],
> embed: [
> 'https://vrm.victronenergy.com/installation/151755/dashboard'
> ]
> }
> },
> 
> What does the CSS configuration in custom.css look like?
> 
> And I havent added the above classes: 'victron' to my custom.css file as it
> is getting the default sizing from the embedURL.css which is the following:
> 
> .MMM-EmbedURL .embed .embeded {
> width: 1200px;
> height: 600px;
> }
> 
> On Mon, Feb 26, 2024 at 5:16 PM Thomas Hirschberger <

**Comment by FuryGear** [comment]
Sorted. Thank you :-)
