### ISSUE TITLE
Override CSS of embedded page? 

### ISSUE THREAD

**Issue by BKeyport** [Tom-Hirschberger/MMM-EmbedURL#16]
I'd like to override CSS of an embedded page locally, much like [here](https://stackoverflow.com/questions/75046526/how-to-load-external-website-into-electron-and-manipulate-persist-its-css-correc)

Basically, I'm using your module to display the "embedded" web view of my weatherstation. Loads correctly, but due to size and distance issues, I'm wanting to change their CSS to show things bigger. At the current time, I'm looking over at the display, and can only see the temp. 

If you'd like to take a look, the embedded website is [here](https://www.weatherlink.com/embeddablePage/show/baf828b34176478196da20eb0e01c34e/fullscreen)

Thanks!

**Comment by Tom-Hirschberger** [comment]
Hi and sorry,

this topic has been discussed a lot.
There seems to be no way to manipulate the CSS of embedded elements (neither Webview nor Iframe).

**Comment by Tom-Hirschberger** [comment]
Hi, 

tried to find a solution again but without success.
Closest thing i found was this thread on stackoverflow: https://stackoverflow.com/questions/217776/how-to-apply-css-to-iframe

But styling of the content of a iframe is not possible at the moment.
I will close the issue for now.
