### ISSUE TITLE
Cookies and zoom on the html page

### ISSUE THREAD

**Issue by 1Cedric1** [Tom-Hirschberger/MMM-EmbedURL#20]
dear @Tom-Hirschberger 
trying to use your module to show an webpage on my magic mirror, I have two basic questions you could maybe answer 

1. cookies : after installing the module and the extension in Chromium on my raspberry, the cookie banner is still appearing after starting the magic mirror every day. 
Do you maybe see a solution ? 
I am not even sure that Chromium is really used by the Magic Mirror to show your module.
![Capture d’écran 2024-09-23 à 11 32 13](https://github.com/user-attachments/assets/7d0ad472-8c43-48d7-bc4a-9505f1a7e0d0)

3. zoom on a specific area of the webpage.

let's say, I would like to show this results table with you module, and not the entire webpage (https://www.teletext.ch/RTSUn/302)
![Capture d’écran 2024-09-26 à 05 01 45](https://github.com/user-attachments/assets/c2a096da-297a-4cba-9fe5-b7003da22adc)

currently, only the upper-right corner is showned.

![Capture d’écran 2024-09-23 à 11 32 13](https://github.com/user-attachments/assets/134721e7-91c4-4925-b63c-d89f4ff5b8d7)

Is that possible to force the module to show only a specific part, e.g. the "green" one. Could maybe that be done through the CSS file, specifiing to show xx dots or cm from the right and from the top of the page.?
do you maybe have an idea?
![Capture d’écran 2024-09-26 à 05 03 43](https://github.com/user-attachments/assets/9eba021e-2757-4489-a8e0-a9003e22fa8d)

Thank you for your interest !

Kind regards,

Cedric

**Comment by Tom-Hirschberger** [comment]
Hi,

looks like you use the build in Electron browser to view the MagicMirror webpage.
So the extension in chromium does effect the embedded page.

There is no easy to hide the banner.
Some pages provide URL parameters to do not display the banner. Maybe you can find one if you inspect the source code of the page.

I added a example to the docs directory of how to embed a webpage displaying a webcam and size and style the page to move only the webcam into the visible area:
 (https://github.com/Tom-Hirschberger/MMM-EmbedURL/tree/main/doc%2Fconfigs)

You need to define the size of embedding container, specify a size with the attributes of the Iframe and move the content of the embedded container.

**Comment by 1Cedric1** [comment]
Thank you very very much @Tom-Hirschberger , it works!
you did an amazing job.
Wishing you all the best !
