### ISSUE TITLE
Module add HTML document structure and not formatting embedded HTML properly

### ISSUE THREAD

**Issue by majurgens** [Tom-Hirschberger/MMM-EmbedURL#8]
I am calling a URL that outputs the following HTML:

`Outside: 16.6<br>Downstairs: 21.0<br>`

Yes, that's all it outputs - super simple, no `<html>`, `<body>`, etc

However, the module seems to be adding an `<html>`, `<body>`, etc, as shown in this screenshot:
![image](https://user-images.githubusercontent.com/16494550/213094728-93f785fa-e97e-4767-b921-f2d848c95705.png)

Possibly related is the problem that I am trying to fix - the final display on the MagicMirror is not formatted according the specified classes (medium, bright, etc)

My config is:
```
   {
     module: "MMM-EmbedURL",
     position: "top_right",
     classes: 'always',
     header: "Live Temp",
     config: {
       updateInterval: 5,
       classes: "medium bright temperature",
       attributes: [
           "frameborder=0",
       ],
       embed: [
           "http://192.168.2.7/cgi-bin/hvac.cgi?func=getliveavgtemp&location=outside,downstairs",
       ]
     },
   },

```

So

**Comment by Tom-Hirschberger** [comment]
Hi,

the MMM-EmbedURL module is designed to embed other complete html pages to the mirror and does not support embedding html snippets. The embedding is realized with iframes in default which results in exactly the code you describe. There is no way to style the content in the iframe.
I searched for alternative ways to implement a kind of templating in this module but could not find any working way.

BUT

You can use two of my other modules to realize exactly what you want.
[MMM-CommandToNotification](https://github.com/Tom-Hirschberger/MMM-CommandToNotification) will fetch the URL periodically with use of the `wget` command and publishes the data as a notification to all other modules.
[MMM-ValuesByNotification](https://github.com/Tom-Hirschberger/MMM-ValuesByNotification) will display the data received with the notification.

This config will cause MMM-CommandToNotification to fetch the URL every 30 seconds:
```json5
		{
			module: "MMM-CommandToNotification",
			disabled: false,
			config: {
				updateInterval: 30,
				commands: [
					{
						script: "/usr/bin/wget",
						args: "-qO - http://192.168.2.7/cgi-bin/hvac.cgi?func=getliveavgtemp&location=outside,downstairs",
						timeout: 5000,
						notifications: [
							"TEMP_OUTSIDE_DOWNSTAIRS",
						],
					},
				]
			},
		},
```

This config will cause MMM-ValuesByNotification to display the values without adding any titles or icons to it. As the data will be added as html elements it is possible to use the styling of the mirror classes:
```json5
		{
			module: "MMM-ValuesByNotification",
			position: "top_center",
			header: "Live Temp",
			config: {
				updateInterval: 30,
				reuseCount: 2,
				groups: [
				{
					items: [
						{
							notification: "TEMP_OUTSIDE_DOWNSTAIRS",
							values: [
								{},
							]
						},
					]
				},
				]
			},
		},
```

Add this elements to your `MagicMirror/css/custom.css` file to avoid a grey border around the values:
```css
.MMM-ValuesByNotification .vbn .groupWrapper {
  border-style: none;
}
```

**Comment by majurgens** [comment]
Thanks for the good response and suggestion. Could you change this module to maybe allow embedElementType = "div" and then the embedded HTML just becomes part of the existing MagicMirror doc?

**Comment by Tom-Hirschberger** [comment]
Hi,

I tried that yesterday but as there is no chance to embed the URL directly that content needs to be fetched before and needs to be written to a template html node that is part of the div.
And that's where things get messy...
Cause of CORS policy of modern browsers this causes a lot of trouble I could not get it realised with this module.

**Comment by majurgens** [comment]
I don't 100% follow. I'll explain why.
I have used this module https://github.com/mykle1/MMM-UFO to grab the same data when in JSON format and inject it into the Magic Mirror. That seems equivalent to me. Grab some data from somewhere and just inject it into a place in the module's area on the screen.

**Comment by Tom-Hirschberger** [comment]
The MMM-UFO is splitted into the typical parts of modules. The node_helper and the MMM-UFO.js.
In this case the node_helper fetches the data and sends it asynchronous to the MMM-UFO.js which displays it.
In the case of this module there is simply no fetch function and I did not implement any communication between the node_helper and the main js class.
To make things clearer. This module is to add html elements
